In [2]:
import numpy as np

In [9]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a.dtype

dtype('int32')

In [11]:
type(a)

numpy.ndarray

In [12]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [14]:
a = a.astype(np.float32) #a = a.astype('float')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [15]:
a[0][1]

2.0

In [16]:
a[0]

array([1., 2., 3.], dtype=float32)

In [18]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(1, 13).reshape(3, 2, 2) #괄호 순으로 이해하면 쉽다

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [24]:
np.nan * 10

nan

In [26]:
a[0][1] = np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [30]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a[0][1] = np.nan #nan 값은 float에서만 사용 가능, int ㄴㄴ
a

ValueError: cannot convert float NaN to integer

In [34]:
a = np.linspace(1, 10, 20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

# 연산

In [36]:
data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [43]:
[1, 2, 3] + [4, 5, 6] #위와의 차이

[1, 2, 3, 4, 5, 6]

In [44]:
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
data * data #각 원소들과의 곱, 행렬의 곱이 아님

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [47]:
np.dot(data, data) #행렬의 곱

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# 차원

In [50]:
#0차원 : 스칼라
a = np.array(1)
a
a.shape
a.ndim #n차원

0

In [52]:
#1차원 : 벡터
a = np.array([1])
a
a.shape
a.ndim #n차원

1

In [54]:
#1차원 : 벡터
a = np.array([1, 2, 3, 4, 5])
a
a.shape #5개의 형태를 가지고 있다

(5,)

In [57]:
#2차원 : 행렬,matrix
a = np.array([[1, 2, 3], [4, 5, 6]])
a
a.shape
#a.ndim #n차원

(2, 3)

In [59]:
#2차원 : 행렬,matrix
a = np.array([[1]])
a
a.shape
a.ndim #n차원

2

In [63]:
# 3차원 : 3차원 이상의 다차원 행렬 Tensor
a = np.array([[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]]])
a
a.shape
a.ndim
#tensorflow == 다차원 행렬을 가지고 연산을 해서 어떠한 결과를 도출하는 것

3

### matrix의 유형

In [65]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [66]:
b = np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
b = np.ones(12).reshape(2, 3, 2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [69]:
c = np.zeros(12).reshape(2, 3, 2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [70]:
d = np.eye(3) #단위행렬 == 자신을 곱했을 때 나오는 행렬
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
e = np.zeros([3, 4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
e = np.zeros([3, 4, 2])
e

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [73]:
f = np.empty([2, 3]) #0에 가까운 값이 있는 값으로 채워줌
f

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [1.69759663e-313, 2.12199579e-313, 2.54639495e-313]])

In [74]:
g = np.full((3, 4), 1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [77]:
h = np.linspace(2, 10, 6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

# 집계함수

In [79]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [82]:
a[0, 1] = 1000 #이런 식으로도 가능
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [83]:
np.mean(a) #평균

114.4

In [84]:
np.median(a) #늘여뜨린 수들 중 가운데 값

6.5

In [85]:
np.std(a) #표준편차

296.5485457728633

In [86]:
np.var(a) #분산

87941.04

In [87]:
np.sum(a) #리스트 내 다더함

1144

In [89]:
 sum(a) #열끼리 더함

array([ 105, 1006,    9,   11,   13])

In [90]:
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [91]:
np.sum(a, axis=0) #열끼리 더함

array([ 105, 1006,    9,   11,   13])

In [92]:
np.sum(a, axis=1) #행끼리 더함

array([1109,   35])

In [93]:
np.max(a) #최대값

1000

In [95]:
np.min(a) #최솟값

2